### ISSUE TITLE
这两天貌似国内有些资源访问不了了

### ISSUE THREAD

**Issue by akring** [onevcat/vno#20]
* 网络：云南电信
* 受影响资源：font-awesome和query，貌似是bootstrapcdn用不了了

目前通过替换BootCDN的CDN解决了，地址分别如下

`//cdn.bootcss.com/font-awesome/4.5.0/css/font-awesome.min.css`
`//cdn.bootcss.com/jquery/3.0.0-alpha1/jquery.min.js`

**Comment by akring** [comment]
应该没问题了，短暂抽疯

**Comment by onevcat** [comment]
T-T 都是不可抗力..
