### ISSUE TITLE
代码折叠问题

### ISSUE THREAD

**Issue by LiboHuang1992** [onevcat/vno#21]
喵大你好, 请问在你的模板中, 如何让Markdown中写的一行代码在长度超过屏幕宽度的时候自动换行, 而不是显示在一行内?

**Comment by onevcat** [comment]
可以试试改一下 `pre` 的样式：http://stackoverflow.com/questions/248011/how-do-i-wrap-text-in-a-pre-tag

不会加到原主题中，我不是很喜欢自动 wrap，特别在小屏幕上会很悲剧。
