### ISSUE TITLE
TOC 集成

### ISSUE THREAD

**Issue by xia50** [onevcat/vno#22]
喵神你好，请问一下这个主题有没有可能集成 一个目录自动生成器（TOC）。因为之前有查过，ghost 不支持 TOC，但是想 github 的 readme 文件都可以 TOC。另外在看你写的文章的时候，因为技术文大多数都很长，所以如果能在开头加一个目录的话，我觉得效果会更好。Ty

**Comment by onevcat** [comment]
没有..我不太喜欢加目录，而且现在主题也没有看到合适的可以加目录的地方..所以并没有打算加这个功能。
