### ISSUE TITLE
脚注并没有变成脚注

### ISSUE THREAD

**Issue by xia50** [onevcat/vno#23]
在使用`[^n]` 时，本应该显示在文字右上角的脚注数字并没有被放在右上角。请问喵神这个怎么修复呢？

**Comment by onevcat** [comment]
据我所知，Ghost 的 Markdown parser 是不会把 `[^n]` 解析成 `<sup>n</sup>`。所以您首先应该向 Ghost 提这个 request 试试看。

另外 vno 目前并没有对 `sup` 做样式，不过这个很容易修正，回头我会加上。

**Comment by xia50** [comment]
嗯，这个确实有上标的显示的，在预览的时候。至于代码里有没有实现我还没去找。
