### ISSUE TITLE
提个问题。关于Disqus和Analytics的

### ISSUE THREAD

**Issue by SeonMe** [onevcat/vno#25]
今天启用了您的主题，发现google analytics无法加载，已确认本地没有网络限制等问题，我是在Ghost 9.0版本中使用，在google analytics调试台也检测不到网站有加载JS；<br/>
还有个就是Disqus评论的问题，不知道您写的CSS关乎到了Disqus的哪个地方，也是一片通红，虽然能正常加载评论框，强迫症，。。。献上地址你看看问题出在何处，我该如何解决这两个问题。<br/>
博客：https://seon.me/

**Comment by onevcat** [comment]
![snip20160810_1](https://cloud.githubusercontent.com/assets/1019875/17539253/ba81d39e-5ee7-11e6-9956-f4d51c24ef93.png)

我这边没发现 Disqus 有什么问题..

GA 的话不清楚...Ghost 现在还自带 GA 了么？我用的那会儿并没有。你可能需要自己在 default.hbs 之类的地方加。

而且这个项目我已经不维护了，已经换到 [Jekyll](https://github.com/onevcat/vno-jekyll) 了。

**Comment by seon212** [comment]
就是我在Ghost后台添加了GA的跟踪代码，chrome开发者模式下看见GA的JS加载不了，还有就是Disqus的，能正常显示，但是一切换到开发者模式下，很多加载项都是加载失败，。。。<br/>
还是感谢您给我解答，我再寻找一下原因。。谢谢
