### ISSUE TITLE
手机访问时“更早”和”最近“不美观

### ISSUE THREAD

**Issue by BruceChao** [onevcat/vno#9]
建议在vno.css中去掉825行 display: block;

**Comment by onevcat** [comment]
十分感谢，我会试试看。

**Comment by Smileyoung** [comment]
域名使用ssl证书，链接从http变为https打开rss无法正常显示，只有在social.hbs RSS那段里面的：{{@blog.url}}/rss/ 改为https://xxx.xxx.xxx/rss/
